/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Triangulation_2;

public interface CGAL_Triangulation_2Constants {
  public final static int CGAL_VERSION_NR = 1040811000;
  public final static int CGAL_SVN_REVISION = 99999;
  public final static String CGAL_VERSION_STR = "4.8.1";
}
